[build]
  command = "PYTHON=python3 npm rebuild sharp && yarn install && yarn build"
  publish = "public"
  environment = { 
    NODE_VERSION = "10.16.0", 
    PYTHON = "python3",
    NPM_VERSION = "6.9.0",
    YARN_VERSION = "1.22.19"
  }