[build]
  command = "yarn install && yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "10.16.0"
  NPM_VERSION = "6.9.0"
  YARN_VERSION = "1.22.19"
  PYTHON = "python3"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"