[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.17"
  NPM_VERSION = "6.9.0"
  YARN_VERSION = "1.22.19"
  PYTHON = "python3"